# Configure Riak connections for the Ripple library.
development:
  port: 8091
  host: localhost

# The test environment has additional keys for configuring the
# Riak::TestServer for your test/spec suite:
#
# * bin_dir specifies the path to the "riak" script that you use to
#           start Riak (just the directory)
# * js_source_dir specifies where your custom Javascript functions for
#           MapReduce should be loaded from. Usually app/mapreduce.
test:
  port: 8091
  host: localhost

production:
  port: 8091
  host: localhost
